/* غرفة قيادة إنسانية: حالة حضور محلية صريحة، منطق نشاط داخل التطبيق فقط، ورسوم Canvas مشتقة من الوقت المسجل بالفعل. */
const STORAGE_KEY = "mad3oom-employee-vanilla-state";
const initialState = { user: null, sessions: [], audit: [], settings: { idleThreshold: 120 }, theme: "light", currentView: "dashboard" };
let state = loadState();
let toastTimer;

function loadState() { try { return { ...initialState, ...JSON.parse(sessionStorage.getItem(STORAGE_KEY) || "{}") }; } catch { return { ...initialState }; } }
function saveState() { sessionStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function id(prefix) { return `${prefix}_${crypto.randomUUID()}`; }
function now() { return Date.now(); }
function clamp(n) { return Math.max(0, Math.floor(n)); }
function formatDuration(value) { const sec = clamp(value); const hours = Math.floor(sec / 3600); const mins = Math.floor((sec % 3600) / 60); const rest = sec % 60; return hours ? `${hours} س ${String(mins).padStart(2, "0")} د` : mins ? `${mins} د ${rest} ث` : `${rest} ث`; }
function formatTime(value) { return new Intl.DateTimeFormat("ar-SA-u-nu-latn", { hour: "2-digit", minute: "2-digit", hour12: false }).format(value); }
function formatDateTime(value) { return new Intl.DateTimeFormat("ar-SA-u-nu-latn", { dateStyle: "short", timeStyle: "short", hour12: false }).format(value); }
function roleLabel(role) { return ({ employee: "موظف", manager: "الموارد البشرية / مدير", super_admin: "مسؤول أعلى" })[role] || "موظف"; }
function currentSession() { return state.sessions.find(item => !item.endedAt) || null; }
function getShift(session, at = now()) { return clamp(((session.endedAt || at) - session.startedAt) / 1000); }
function getBreak(session, at = now()) { return session.breaks.reduce((sum, item) => sum + clamp(((item.endedAt || at) - item.startedAt) / 1000), 0); }
function status(session) { if (!session) return "OFFLINE"; if (session.breaks.at(-1) && !session.breaks.at(-1).endedAt) return "BREAK"; return atIdle(session) ? "IDLE" : "ACTIVE"; }
function statusLabel(value) { return ({ OFFLINE: "خارج الوردية", ACTIVE: "نشط الآن", IDLE: "خامل الآن", BREAK: "في استراحة" })[value]; }
function atIdle(session) { return now() - session.lastActivityAt >= state.settings.idleThreshold * 1000; }
function dayStart(at = now()) { const date = new Date(at); date.setHours(0, 0, 0, 0); return date.getTime(); }
function overlapSeconds(start, end, startRange, endRange) { return clamp((Math.min(end, endRange) - Math.max(start, startRange)) / 1000); }
function dailySummary() { const start = dayStart(); const userId = state.user?.id; return state.sessions.reduce((total, session) => { if (session.userId !== userId) return total; const end = Math.min(session.endedAt || now(), now()); const shift = overlapSeconds(session.startedAt, end, start, now()); if (!shift) return total; const breaks = session.breaks.reduce((sum, item) => sum + overlapSeconds(item.startedAt, Math.min(item.endedAt || now(), now()), start, now()), 0); total.sessions += 1; total.shift += shift; total.break += breaks; total.work += Math.max(0, shift - breaks); return total; }, { sessions: 0, shift: 0, work: 0, break: 0 }); }
function log(action, details) { if (!state.user) return; state.audit.unshift({ id: id("audit"), at: now(), action, details, actor: state.user.name }); state.audit = state.audit.slice(0, 100); }
function toast(message) { const element = document.querySelector("#toast"); element.textContent = message; element.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => element.classList.remove("show"), 3400); }
function recordActivity(label = "تفاعل داخل التطبيق") { const session = currentSession(); if (!session || status(session) === "BREAK") return; session.lastActivityAt = now(); session.lastTickAt = now(); if (!session.timeline.length || now() - session.timeline[0].at > 45000) session.timeline.unshift({ id: id("event"), at: now(), label, type: "activity" }); saveState(); }
function advanceClock() { const session = currentSession(); if (!session || document.visibilityState !== "visible") return; const timestamp = now(); const delta = Math.min(5, clamp((timestamp - session.lastTickAt) / 1000)); if (!delta) return; const before = status(session); if (before === "BREAK") { session.lastTickAt = timestamp; saveState(); render(); return; } if (atIdle(session)) session.idleSeconds += delta; else session.activeSeconds += delta; session.lastTickAt = timestamp; saveState(); render(); }
function beginSession(name, role) { state.user = { id: id("user"), name, role, startedAt: now() }; log("تسجيل دخول", "تم إنشاء جلسة محلية داخل المتصفح."); saveState(); toast("تم بدء الجلسة المحلية."); render(); }
function logout() { if (!state.user) { toast("لا توجد جلسة محلية لإنهائها."); return; } state = { ...initialState, theme: state.theme, settings: state.settings }; saveState(); toast("تم إنهاء الجلسة وتنظيف سجلاتها المحلية."); render(); }
function startShift() { if (!state.user) { document.querySelector("#session-dialog").showModal(); return; } if (currentSession()) { toast("لديك وردية مفتوحة بالفعل."); return; } const time = now(); state.sessions.unshift({ id: id("shift"), userId: state.user.id, startedAt: time, endedAt: null, breaks: [], activeSeconds: 0, idleSeconds: 0, lastActivityAt: time, lastTickAt: time, timeline: [{ id: id("event"), at: time, label: "بدأت الوردية", type: "attendance" }] }); log("بدء وردية", "تم بدء وردية محلية."); saveState(); toast("بدأت الوردية وسُجل وقت البداية محليًا."); render(); }
function startBreak() { const session = currentSession(); if (!session) return toast("ابدأ وردية قبل بدء الاستراحة."); if (status(session) === "BREAK") return toast("الاستراحة قائمة بالفعل."); session.breaks.push({ id: id("break"), startedAt: now(), endedAt: null }); session.timeline.unshift({ id: id("event"), at: now(), label: "بدأت الاستراحة", type: "break" }); log("بدء استراحة", "تم بدء استراحة محلية."); saveState(); toast("بدأت الاستراحة وتوقف عداد النشاط."); render(); }
function endBreak() { const session = currentSession(); if (!session || status(session) !== "BREAK") return toast("لا توجد استراحة مفتوحة لإنهائها."); session.breaks.at(-1).endedAt = now(); session.lastActivityAt = now(); session.lastTickAt = now(); session.timeline.unshift({ id: id("event"), at: now(), label: "انتهت الاستراحة وعاد النشاط", type: "break" }); log("إنهاء استراحة", "تم إنهاء الاستراحة محليًا."); saveState(); toast("انتهت الاستراحة وعاد عداد النشاط."); render(); }
function endShift() { const session = currentSession(); if (!session) return toast("لا توجد وردية مفتوحة لإنهائها."); const time = now(); if (status(session) === "BREAK") session.breaks.at(-1).endedAt = time; session.endedAt = time; session.timeline.unshift({ id: id("event"), at: time, label: "انتهت الوردية", type: "attendance" }); log("إنهاء وردية", "تم إنهاء الوردية وحفظ ملخصها محليًا."); saveState(); toast("انتهت الوردية وحفظ ملخصها داخل الجلسة."); render(); }
function getHeader(view) { const data = { dashboard: ["لوحة العمليات", "حالة الوردية والنشاط المرصود داخل هذه الواجهة فقط."], reports: ["التقارير المحلية", "ملخص من السجلات التي أنشئت في جلسة هذا المتصفح."], audit: ["سجل التدقيق", "أثر محلي للإجراءات المهمة داخل الجلسة."], settings: ["إعدادات الجلسة", "تحكم محلي في عتبة الخمول وتفضيلات العرض."] }[view]; return data; }
function statusPill(session) { const value = status(session); const cls = value === "OFFLINE" ? "offline" : value.toLowerCase(); return `<span class="status-pill ${cls}">${statusLabel(value)}</span>`; }
function metric(label, value, hint, tone = "") { return `<article class="metric ${tone}"><p>${label}</p><strong>${value}</strong><span>${hint}</span></article>`; }
function dashboard() { const session = currentSession(); const summary = dailySummary(); const active = session?.activeSeconds || 0; const idle = session?.idleSeconds || 0; const breakSeconds = session ? getBreak(session) : 0; const shift = session ? getShift(session) : 0; return `<section class="hero"><div><p class="eyebrow">الحالة الحالية</p><h2>${session ? statusLabel(status(session)) : "لا توجد وردية مفتوحة"}</h2><p>${session ? `بدأت الوردية عند <strong>${formatTime(session.startedAt)}</strong>، وتُحتسب الأوقات ضمن علامة التبويب النشطة.` : "ابدأ وردية ليتفعّل احتساب الحضور والنشاط والخمول محليًا."}</p></div><div class="hero-actions">${session ? (status(session) === "BREAK" ? `<button class="primary-button" data-action="end-break">إنهاء الاستراحة</button>` : `<button class="secondary-button" data-action="start-break">بدء استراحة</button>`) + `<button class="danger-button" data-action="end-shift">إنهاء العمل</button>` : `<button class="primary-button" data-action="start-shift">بدء العمل</button>`}</div></section><section class="metrics">${metric("مدة الوردية", formatDuration(shift), session ? "منذ بدء الوردية" : "بانتظار بدء وردية")}${metric("وقت النشاط", formatDuration(active), "تفاعل داخل التطبيق", "sage")}${metric("وقت الخمول", formatDuration(idle), `العتبة: ${state.settings.idleThreshold} ث`, "sand")}${metric("وقت الاستراحة", formatDuration(breakSeconds), "خارج النشاط والخمول", "rose")}</section>${dailyCharts(summary)}<section class="lower-grid"><article class="panel"><div class="panel-head"><div><p class="eyebrow">السجل الزمني</p><h2>آخر ما حدث في الوردية</h2></div>${session ? `<span class="badge">${activityPercent(session)}% نشاط</span>` : ""}</div>${timeline(session)}</article><article class="panel scope"><p class="eyebrow">مؤشر الجلسة</p><h2>نطاق التتبع</h2><div class="scope-art"><svg viewBox="0 0 240 100" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 76h200M38 20v55M86 35v40M134 12v63M182 28v47" opacity=".3"/><path d="M26 64h46l20-22h42l21-17h52" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><circle cx="26" cy="64" r="5" fill="currentColor"/><circle cx="92" cy="42" r="5" fill="currentColor"/><circle cx="155" cy="25" r="5" fill="currentColor"/><circle cx="207" cy="25" r="5" fill="currentColor"/></svg></div><strong>داخل مدعوم فقط</strong><p>يرصد التطبيق التفاعل والتنقل داخل واجهته؛ لا يجمع بيانات من خارجها.</p></article></section>`; }
function dailyCharts(summary) { if (!summary.sessions) return `<section class="daily"><div class="panel-head"><div><p class="eyebrow">الملخص اليومي</p><h2>وقت العمل والاستراحات</h2></div></div><div class="empty-state"><span class="empty-mark">◌</span><h3>لا توجد وردية بدأت اليوم</h3><p>ستظهر الرسوم تلقائيًا بعد بدء وردية محلية، من دون إنشاء أرقام أو سجلات افتراضية.</p></div></section>`; return `<section class="daily"><header class="daily-head"><div><p class="eyebrow">الملخص اليومي</p><h2>وقت العمل والاستراحات</h2><p>تُحسب الدقائق الواقعة ضمن اليوم الحالي فقط، حتى عند امتداد الوردية من يوم سابق.</p></div><div class="daily-total"><span>إجمالي الوردية اليوم</span><strong>${formatDuration(summary.shift)}</strong></div></header><div class="chart-grid"><article class="panel"><div class="chart-head"><div><h3>توزيع الوردية</h3><p>مقارنة مباشرة بين العمل والاستراحات.</p></div><span>${summary.sessions} وردية</span></div><div class="chart-box"><canvas id="work-chart" aria-label="رسم وقت العمل والاستراحة"></canvas></div><div class="legend"><span><i></i>وقت العمل <b>${formatDuration(summary.work)}</b></span><span><i class="sand"></i>الاستراحة <b>${formatDuration(summary.break)}</b></span></div></article><article class="panel"><div class="chart-head"><div><h3>نسبة وقت الاستراحة</h3><p>المساحة المتبقية تمثل وقت العمل الصافي.</p></div><span>اليوم الحالي</span></div><div class="chart-box"><canvas id="break-chart" aria-label="رسم نسبة الاستراحة"></canvas></div><div class="legend"><span><i></i>وقت العمل الصافي <b>${formatDuration(summary.work)}</b></span><span><i class="sand"></i>وقت الاستراحة <b>${formatDuration(summary.break)}</b></span></div></article></div></section>`; }
function activityPercent(session) { const net = Math.max(0, getShift(session) - getBreak(session)); return net ? Math.min(100, Math.round((session.activeSeconds / net) * 100)) : 0; }
function timeline(session) { if (!session?.timeline.length) return `<div class="empty-state"><span class="empty-mark">○</span><h3>لا توجد أحداث بعد</h3><p>ستظهر تحركات الوردية والاستراحة هنا بعد بدء العمل.</p></div>`; return `<ol class="timeline">${session.timeline.slice(0, 8).map(event => `<li><span class="timeline-icon">${event.type === "break" ? "☕" : event.type === "attendance" ? "●" : "◌"}</span><div><strong>${event.label}</strong><small>${formatDateTime(event.at)}</small></div></li>`).join("")}</ol>`; }
function reports() { const sessions = state.sessions.filter(item => item.userId === state.user?.id); if (!sessions.length) return `<section class="panel"><div class="empty-state"><span class="empty-mark">◫</span><h3>لا توجد تقارير بعد</h3><p>ابدأ وردية ثم أنهِها لإنشاء تقرير محلي حقيقي.</p></div></section>`; return `<section class="panel"><div class="panel-head"><div><p class="eyebrow">تفصيل الوردية</p><h2>السجلات المحلية</h2></div><span class="badge">${sessions.length} سجل</span></div><div class="table-wrap"><table><thead><tr><th>البداية</th><th>النهاية</th><th>مدة الوردية</th><th>الاستراحة</th><th>النشاط</th></tr></thead><tbody>${sessions.map(session => `<tr><td>${formatDateTime(session.startedAt)}</td><td>${session.endedAt ? formatDateTime(session.endedAt) : "مستمرة"}</td><td>${formatDuration(getShift(session))}</td><td>${formatDuration(getBreak(session))}</td><td>${activityPercent(session)}%</td></tr>`).join("")}</tbody></table></div></section>`; }
function audit() { if (!state.audit.length) return `<section class="panel"><div class="empty-state"><span class="empty-mark">◌</span><h3>السجل فارغ</h3><p>ستظهر هنا عمليات بدء الجلسة والوردية والاستراحة فور تنفيذها.</p></div></section>`; return `<section class="panel"><div class="panel-head"><div><p class="eyebrow">الأحداث المسجلة</p><h2>تسلسل إجراءات الجلسة</h2></div></div><ol class="timeline">${state.audit.map(item => `<li><span class="timeline-icon">●</span><div><strong>${item.action}</strong><small>${item.details} — ${formatDateTime(item.at)}</small></div></li>`).join("")}</ol></section>`; }
function settings() { return `<section class="settings-layout"><form id="settings-form" class="panel setting-card"><span class="setting-icon">◷</span><div><p class="eyebrow">منطق الخمول</p><h2>عتبة عدم التفاعل</h2><p>بعد هذه المدة بلا تفاعل داخل التطبيق، تتحول حالة الوردية إلى خامل.</p></div><label class="setting-control">ثوانٍ<input id="idle-threshold" type="number" min="30" max="1800" value="${state.settings.idleThreshold}" /></label><button class="primary-button" type="submit">حفظ العتبة</button></form><section class="panel setting-card"><span class="setting-icon">◐</span><div><p class="eyebrow">تفضيل الواجهة</p><h2>المظهر</h2><p>يطبق داخل المتصفح الحالي على كامل الواجهة.</p></div><div class="theme-options"><button type="button" data-theme="light" class="${state.theme === "light" ? "selected" : ""}">فاتح</button><button type="button" data-theme="dark" class="${state.theme === "dark" ? "selected" : ""}">داكن</button></div></section><section class="notice"><span>!</span><div><strong>حدود هذه النسخة</strong><p>لا تشكل الجلسة أو الصلاحيات أو سجل التدقيق حماية أمنية؛ هذا تطبيق محلي لا يملك خادمًا أو قاعدة بيانات.</p></div></section></section>`; }
function render() { document.documentElement.classList.toggle("dark", state.theme === "dark"); const [title, subtitle] = getHeader(state.currentView); document.querySelector("#page-title").textContent = title; document.querySelector("#page-subtitle").textContent = subtitle; document.querySelector("#theme-button span:last-child").textContent = state.theme === "dark" ? "فاتح" : "داكن"; document.querySelector("#account-name").textContent = state.user?.name || "بدون مستخدم"; document.querySelector("#account-role").textContent = state.user ? roleLabel(state.user.role) : "أنشئ جلسة محلية"; document.querySelector("#avatar").textContent = state.user?.name.slice(0, 1) || "م"; document.querySelector("#sidebar-status").textContent = currentSession() ? statusLabel(status(currentSession())) : state.user ? "لا توجد وردية مفتوحة" : "لم تُعرّف بعد"; document.querySelector("#logout-button").style.visibility = state.user ? "visible" : "hidden"; document.querySelectorAll("[data-view]").forEach(button => button.classList.toggle("active", button.dataset.view === state.currentView)); const view = { dashboard, reports, audit, settings }[state.currentView]; document.querySelector("#view-root").innerHTML = view(); if (state.currentView === "dashboard" && dailySummary().sessions) requestAnimationFrame(drawCharts); }
function canvasSize(canvas) { const dpr = window.devicePixelRatio || 1; const rect = canvas.getBoundingClientRect(); canvas.width = rect.width * dpr; canvas.height = rect.height * dpr; const ctx = canvas.getContext("2d"); ctx.scale(dpr, dpr); return { ctx, width: rect.width, height: rect.height }; }
function drawCharts() { const summary = dailySummary(); const styles = getComputedStyle(document.documentElement); const teal = styles.getPropertyValue("--teal").trim(); const sand = styles.getPropertyValue("--sand").trim(); const inkSoft = styles.getPropertyValue("--ink-soft").trim(); const surface = styles.getPropertyValue("--surface").trim(); const work = document.querySelector("#work-chart"); const pie = document.querySelector("#break-chart"); if (!work || !pie) return; { const { ctx, width, height } = canvasSize(work); const max = Math.max(1, summary.shift); const barX = 24, barY = height / 2 - 22, barW = width - 48, barH = 44; ctx.fillStyle = surface; ctx.fillRect(0,0,width,height); ctx.fillStyle = "#d9e1db"; ctx.beginPath(); ctx.roundRect(barX,barY,barW,barH,9); ctx.fill(); const workW = Math.max(0, barW * summary.work / max); const breakW = Math.max(0, barW * summary.break / max); ctx.fillStyle = teal; ctx.beginPath(); ctx.roundRect(barX,barY,workW,barH,9); ctx.fill(); if (breakW) { ctx.fillStyle = sand; ctx.beginPath(); ctx.roundRect(barX + workW,barY,breakW,barH,9); ctx.fill(); } ctx.fillStyle = inkSoft; ctx.font = "11px IBM Plex Sans Arabic"; ctx.textAlign = "center"; ctx.fillText(formatDuration(summary.shift), width / 2, barY + 74); } { const { ctx, width, height } = canvasSize(pie); const centerX = width/2, centerY = height/2, radius = Math.min(width,height)*.31, line = 22, percent = summary.shift ? summary.break / summary.shift : 0; ctx.fillStyle = surface; ctx.fillRect(0,0,width,height); ctx.lineWidth = line; ctx.lineCap = "round"; ctx.strokeStyle = teal; ctx.beginPath(); ctx.arc(centerX,centerY,radius,0,Math.PI*2); ctx.stroke(); if (percent) { ctx.strokeStyle = sand; ctx.beginPath(); ctx.arc(centerX,centerY,radius,-Math.PI/2,-Math.PI/2 + Math.PI*2*percent); ctx.stroke(); } ctx.fillStyle = inkSoft; ctx.font = "11px IBM Plex Sans Arabic"; ctx.textAlign="center"; ctx.fillText("استراحة",centerX,centerY-2); ctx.fillStyle = styles.getPropertyValue("--ink").trim(); ctx.font = "700 17px Noto Kufi Arabic"; ctx.fillText(`${Math.round(percent*100)}%`,centerX,centerY+23); } }
function bindEvents() { document.addEventListener("click", event => { const trigger = event.target.closest("[data-view]"); if (trigger) { state.currentView = trigger.dataset.view; saveState(); render(); } const action = event.target.closest("[data-action]")?.dataset.action; if (action === "start-shift") startShift(); if (action === "start-break") startBreak(); if (action === "end-break") endBreak(); if (action === "end-shift") endShift(); const theme = event.target.closest("[data-theme]")?.dataset.theme; if (theme) { state.theme = theme; saveState(); render(); } if (event.target.closest("#theme-button")) { state.theme = state.theme === "dark" ? "light" : "dark"; saveState(); render(); } if (event.target.closest("#session-button")) document.querySelector("#session-dialog").showModal(); if (event.target.closest("#logout-button")) logout(); if (event.target.closest("[data-close-dialog]")) document.querySelector("#session-dialog").close(); }); document.querySelector("#session-form").addEventListener("submit", event => { event.preventDefault(); const name = document.querySelector("#display-name").value.trim(); const role = document.querySelector("#role").value; if (name.length < 2) return toast("اكتب اسم عرض من حرفين على الأقل."); beginSession(name, role); document.querySelector("#session-dialog").close(); }); document.addEventListener("pointerdown", () => recordActivity()); document.addEventListener("keydown", () => recordActivity()); window.addEventListener("focus", () => recordActivity("عاد المستخدم إلى النظام")); document.addEventListener("resize", () => { if (state.currentView === "dashboard" && dailySummary().sessions) requestAnimationFrame(drawCharts); }); }
bindEvents(); render(); window.setInterval(advanceClock, 1000);
