/** أسلوب غرفة قيادة إنسانية: شريط جانبي يميني ثابت ومساحة عمل غير متماثلة تضع الزمن وحالة الفريق قبل الزخرفة. */
import { BarChart3, ClipboardList, LayoutDashboard, LogOut, Moon, Settings, ShieldCheck, Sun, UsersRound } from "lucide-react";
import { Link, useLocation } from "wouter";
import { BrandMark } from "@/components/BrandMark";
import { StatusPill } from "@/components/Ui";
import { useAppearance } from "@/contexts/AppearanceContext";
import { useOperations } from "@/contexts/OperationsContext";
const navigation = [{ href: "/لوحة-التحكم", label: "لوحة العمليات", icon: LayoutDashboard },{ href: "/لوحة-المدير", label: "لوحة المدير", icon: UsersRound, managerOnly: true },{ href: "/التقارير", label: "التقارير", icon: BarChart3, managerOnly: true },{ href: "/سجل-التدقيق", label: "سجل التدقيق", icon: ClipboardList, managerOnly: true },{ href: "/الإعدادات", label: "الإعدادات", icon: Settings, adminOnly: true }];
export function AppShell({ children, title, subtitle }: { children: React.ReactNode; title: string; subtitle: string }) { const [location] = useLocation(); const { user, currentSession, canViewManagement, logout, recordInteraction } = useOperations(); const { resolvedTheme, setTheme } = useAppearance(); const visibleItems = navigation.filter((item) => (!item.managerOnly || canViewManagement) && (!item.adminOnly || user?.role === "super_admin")); return <div className="app-shell" dir="rtl"><aside className="sidebar"><div className="brand-lockup"><BrandMark size={46} /><div><span>مدعوم</span><strong>عمليات الموظفين</strong></div></div><div className="sidebar-rule" /><nav aria-label="التنقل الرئيسي">{visibleItems.map((item) => { const Icon = item.icon; return <Link key={item.href} href={item.href} className={`nav-link ${location === item.href ? "active" : ""}`} onClick={() => recordInteraction(`انتقل إلى ${item.label}`, "navigation")}><Icon size={19} /><span>{item.label}</span></Link>; })}</nav><div className="sidebar-bottom"><div className="session-summary"><span className="mini-label">الجلسة المحلية</span>{currentSession ? <StatusPill status={currentSession.status} /> : <span className="offline-label">لا توجد وردية مفتوحة</span>}</div><div className="account-card"><span className="account-initial">{user?.displayName.slice(0, 1)}</span><div><strong>{user?.displayName}</strong><small>{user?.role === "super_admin" ? "مسؤول أعلى" : user?.role === "manager" ? "مدير" : "موظف"}</small></div></div><button className="signout-button" type="button" onClick={logout}><LogOut size={18} /> إنهاء الجلسة</button></div></aside><main className="workspace"><header className="workspace-header"><div><p className="eyebrow">مدعوم / عمليات الموظفين</p><h1>{title}</h1><p className="header-subtitle">{subtitle}</p></div><button className="theme-button" type="button" onClick={() => setTheme(resolvedTheme === "dark" ? "light" : "dark")} aria-label="تبديل المظهر">{resolvedTheme === "dark" ? <Sun size={19} /> : <Moon size={19} />}<span>{resolvedTheme === "dark" ? "فاتح" : "داكن"}</span></button></header>{children}</main></div>; }
export function AccessDenied() { return <div className="access-denied"><ShieldCheck size={32} /><h2>هذه الصفحة ضمن صلاحيات الإدارة</h2><p>تُطبَّق الصلاحيات هنا على الواجهة والمنطق المحلي فقط.</p><Link href="/لوحة-التحكم" className="primary-button">العودة إلى لوحة العمليات</Link></div>; }
